from sqlalchemy import text


def seed_cookies(op):
    fortune_cookies = [
        "A beautiful, smart, and loving person will be coming into your life.",
        "A fresh start will put you on your way.",
        "A golden opportunity is coming your way.",
        "A lifetime of happiness lies ahead of you.",
        "A pleasant surprise is waiting for you.",
        "All your hard work will soon pay off.",
        "An exciting adventure awaits you.",
        "Believe in yourself and others will too.",
        "Change can hurt, but it leads a path to something better.",
        "Do not be afraid to take that big step.",
        "Every day is a new beginning.",
        "Fortune favors the brave.",
        "Good news will come to you by mail.",
        "Happiness begins with facing life with a smile and a wink.",
        "If you continually give, you will continually have.",
        "It is now, and in this world, that we must live.",
        "Now is the time to try something new.",
        "Opportunities are all around you if you just look.",
        "Patience is a virtue, and it will be rewarded soon.",
        "People are naturally attracted to you.",
        "Success is a journey, not a destination.",
        "The fortune you seek is in another cookie.",
        "The greatest risk is not taking one.",
        "You are capable of achieving great things.",
        "You are never selfish with your advice or your help.",
        "You will achieve your goals if you stay focused.",
        "You will have a pleasant surprise soon.",
        "You will make a change for the better.",
        "Your ability for accomplishment will follow with success.",
        "Your life will be happy and peaceful.",
        "A wise person learns from the mistakes of others.",
        "Adventure can be real happiness.",
        "Be brave and take risks, nothing can substitute experience.",
        "Courage is not the absence of fear, but action in spite of it.",
        "Dreams are the windows to your future.",
        "Embrace this moment, remember we are eternal.",
        "Find release from your cares, have a good time.",
        "Give to the world the best you have and the best will come to you.",
        "Help is always needed but not always appreciated.",
        "In the end, we only regret chances we didn't take.",
        "Judge each day not by the harvest but by the seeds you plant.",
        "Keep your face always toward the sunshine and shadows will fall behind you.",
        "Life is what happens when you're busy making other plans.",
        "Make peace with your past so it doesn't spoil your present.",
        "Nothing is impossible to a willing heart.",
        "Open your eyes to the beauty around you.",
        "Prosperity will knock on your door soon.",
        "Quality, not quantity, is what matters.",
        "Remember that failure is an event, not a person.",
        "Small steps every day lead to big changes in a year.",
        "The best is yet to come.",
        "Understanding yourself is the key to wisdom.",
        "Value your friendships above all else.",
        "What doesn't kill you makes you stronger.",
        "Your kindness will be returned to you tenfold.",
        "Zen is not what you think.",
        "A faithful friend is a strong defense.",
        "A feather in the hand is better than a bird in the air.",
        "A friend asks only for your time, not your money.",
        "A friend is a present you give yourself.",
        "A gambler not only will lose what he has, but also will lose what he doesn’t have.",
        "A good way to keep healthy is to eat more Chinese food.",
        "A lifetime friend shall soon be made.",
        "A light heart carries you through all the hard times.",
        "A new perspective will come with the new year.",
        "A person is never too old to learn.",
        "A smile is your personal welcome mat.",
        "A soft voice may be awfully persuasive.",
        "A truly rich life contains love and art in abundance.",
        "Accept something that you cannot change, and you will feel better.",
        "Adventure awaits you this weekend.",
        "All your sorrows will vanish.",
        "An inch of time is an inch of gold.",
        "An unexpected event will soon make your life more exciting.",
        "Be careful or you could fall for some tricks today.",
        "Beauty in its various forms appeals to you.",
        "Because you demand more from yourself, others respect you deeply.",
        "Believe it can be done.",
        "Bide your time, for success is near.",
        "Carve your name on your heart and not on marble.",
        "Competence like yours is underrated.",
        "Congratulations! You are on your way.",
        "Courtesy begins in the home.",
        "Dedicate yourself with a calm mind to the task at hand.",
        "Depart not from the path which fate has assigned you.",
        "Determination is what you need now.",
        "Disbelief destroys the magic.",
        "Distance yourself from the vain.",
        "Do not let ambitions overshadow small success.",
        "Do not make extra work for yourself.",
        "Do not underestimate yourself.",
        "Don’t just spend time. Invest it.",
        "Don’t let friends impose on you, work calmly and silently.",
        "Don’t let the past and useless detail choke your existence.",
        "Don’t worry; prosperity will knock on your door soon.",
        "Each day, compel yourself to do something you would rather not do.",
        "Education is the ability to meet life’s situations.",
        "Embrace change, don’t fear it.",
        "Every flower blooms in its own sweet time.",
        "Every wise man started out by asking many questions.",
        "Everyday in your life is a special occasion.",
        "Failure is the tuition you pay for success.",
        "Fearless courage is the foundation of victory.",
        "Fortune not found: abort, retry, ignore?",
        "From now on your kindness will lead you to success.",
        "Go take a rest; you deserve it.",
        "Good luck is the result of good planning.",
        "Happiness is an activity.",
        "Hard work pays off in the future, laziness pays off now.",
        "He who laughs at himself never runs out of things to laugh at.",
        "If you look in the right places, you can find some good offerings.",
        "If you want the rainbow, you have to tolerate the rain.",
        "If your desires are not extravagant, they will be granted.",
        "In order to take, one must first give.",
        "It is better to deal with problems before they arise.",
        "It is better to light one small candle than to curse the darkness.",
        "It takes courage to admit fault.",
        "It’s amazing how much good you can do if you don’t care who gets the credit.",
        "Let the deeds speak.",
        "Listen to everyone. Ideas come from everywhere.",
        "Long life is in store for you.",
        "Love is a warm fire to keep the soul warm.",
        "Love lights up the world.",
        "Many will travel to hear you speak.",
        "Meditation with an old enemy is advised.",
        "Miles are covered one step at a time.",
        "Nature, time and patience are the three great physicians.",
        "Never fear! The end of something marks the start of something new.",
        "No one can walk backwards into the future.",
        "Now is the time to try something new.",
        "One can never fill another’s shoes, rather he must outgrow the old shoes.",
        "One of the first things you should look for in a problem is its positive side.",
        "Others can help you now.",
        "People find it difficult to resist your persuasive manner.",
        "People who are late are often happier than those who have to wait for them.",
        "Practice makes perfect.",
        "Protective measures will prevent costly disasters.",
        "Put your mind into planning today. Look into the future.",
        "Rest has a peaceful effect on your physical and emotional health.",
        "Resting well is as important as working hard.",
        "Say hello to others. You will have a happier day.",
        "Serious trouble will bypass you.",
        "Simplicity and clarity should be your theme in dress.",
        "Sloth makes all things difficult; industry all easy.",
        "Small confidences mark the onset of a friendship.",
        "Someone you care about seeks reconciliation.",
        "Soon life will become more interesting.",
        "Stand tall. Don’t look down upon yourself.",
        "Success is a journey, not a destination.",
        "The harder you work, the luckier you get.",
        "The man on the top of the mountain did not fall there.",
        "The only certainty is that nothing is certain.",
        "The secret of getting ahead is getting started.",
        "There is a time for caution, but not for fear.",
        "There is no greater pleasure than seeing your loved ones prosper.",
        "Things may come to those who wait, but only the things left by those who hustle.",
        "This is a good time to finish up old tasks.",
        "Those who care will make the effort.",
        "To courageously shoulder the responsibility of one’s mistake is character.",
        "Today is the day to show someone you care.",
        "Use your abilities at this time to stay focused on your goal.",
        "Wealth awaits you very soon.",
        "When fear hurts you, conquer it and defeat it!",
        "When one door closes, another opens.",
        "With age comes wisdom.",
        "You are admired by everyone for your talent and ability.",
        "You are almost there.",
        "You are busy, but you are happy.",
        "You are generous to an extreme and always think of the other fellow.",
        "You are going to have some new clothes.",
        "You are in good hands this evening.",
        "You are modest and courteous.",
        "You are never selfish with your advice or your help.",
        "You are the master of every situation.",
        "You can make your own happiness.",
        "You have a deep appreciation of the arts and music.",
        "You have a reputation for being straightforward and honest.",
        "You have an active mind and a keen imagination.",
        "You have had a good start. Work harder!",
        "You will always be surrounded by true friends.",
        "You will always get what you want through your charm and personality.",
        "You will be called in to fulfill a position of high honor and responsibility.",
        "You will be successful in your work.",
        "You will become great if you believe in yourself.",
        "You will discover an unexpected treasure.",
        "You will have a long and healthy life.",
        "You will make a change for the better.",
        "Your ability for accomplishment will follow with success.",
        "Your happiness is before you, not behind you! Cherish it.",
        "Your life will be happy and peaceful.",
    ]

    for description in fortune_cookies:
        op.execute(
            text("INSERT INTO cookies (text) VALUES (:text);").bindparams(
                text=description
            )
        )
