"""structure

Revision ID: c5296ad37f6e
Revises: 
Create Date: 2025-07-09 09:06:10.658849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5296ad37f6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    if not bool(None):
        from migrations.seeds import seed
        seed(op)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookies')
    # ### end Alembic commands ###
